config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'home#index'
  root 'home#index'

  resources :users, only: [:new, :create, :edit, :update]
  resources :posts, only: [:index, :new, :create]

  post 'delete_all_post' => 'posts#delete_all_post'

  get 'login' => 'sessions#getLogin'
  post 'login' => 'sessions#postLogin'
  delete 'logout' => 'sessions#deleteLogout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, uniqueness: { case_sensitive: false }, on: :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }, on: :create
  VALID_IMAGE_REGEX = /.*(jpeg|jpg|gif|png)\Z/
  validates :image, presence: true, format: { with: VALID_IMAGE_REGEX }, on: :create

  validates :name, uniqueness: { case_sensitive: false }, on: :update
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }, on: :update
  VALID_IMAGE_REGEX = /.*(jpeg|jpg|gif|png)\Z/
  validates :image, format: { with: VALID_IMAGE_REGEX }, on: :update

  validates :password, length: {minimum: 4}, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user

  def index
    @posts = Post.all
  end

  def new
    # necessary for validation error message
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.message = params[:message]
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def delete_all_post
    Post.delete_all
    redirect_to posts_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def getLogin
    render 'login'
  end

  def postLogin
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      login user
      flash[:success] = 'You have successfully logged in'
      redirect_to posts_path
    else
      flash[:failure] = 'There was a problem with your email or password'
      render 'login'
    end
  end

  def deleteLogout
    logout
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]

  def new
    # necessary for validation error message
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]

    if params[:file].present?
      image_file = params[:file]
      time = Time.now
      name = time.to_s + image_file.original_filename

      File.open("#{Rails.public_path}/images/#{name}", 'wb') { |f|
        f.write(image_file.read)
      }

      @user.image = name
    end

    if @user.save
      login @user
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    update_params = {}

    if params[:name].present?
      update_params[:name] = params[:name]
    end
    if params[:email].present?
      update_params[:email] = params[:email]
    end
    if params[:password].present?
      update_params[:password] = params[:password]
    end
    if params[:file].present?
      old_image_file = "#{Rails.public_path}/images/#{@user.image}"

      image_file = params[:file]
      time = Time.now
      name = time.to_s + image_file.original_filename
      update_params[:image] = name
    end

    if update_params.empty?
      render 'edit'
    elsif @user.update(update_params)
      if params[:file].present?
        File.open("#{Rails.public_path}/images/#{name}", 'wb') { |f|
          f.write(image_file.read)
        }
        File.delete(old_image_file)
      end
      login @user
      redirect_to posts_path
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?
      redirect_to login_path
    end
  end
end

app/views/home/index.html.erb
<% content_for :title do %>
グループ交流アプリ
<% end %>

<div class="jumbotron">
  <h1>グループ交流アプリ</h1>
  <p>本アプリケーションは○○グループのメンバー間で情報共有を行うためのWebアプリケーションです。未登録の方は下記のボタンを押して登録をお願いします。</p>
  <a class="btn btn-primary" href="<%= new_user_path %>" role="button">登録画面へ</a>
</div>

app/views/layouts/_error_message.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <strong>Errors:</strong>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_message.html.erb
<% flash.each do |key, value| %>
  <% if key == "success" %>
    <div class="alert alert-success">
      <strong>Success:</strong><%= value %>
    </div>
  <% elsif key == "failure" %>
    <div class="alert alert-danger">
      <strong>Failure:</strong><%= value %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= home_path %>">ホーム</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
      <ul class="nav navbar-nav">
        <li><a href="<%= posts_path %>">トーク画面</a></li>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><a href="<%= edit_user_path(:id => current_user.id) %>"><%= current_user.name %>さんようこそ</a></li>
        <li>
          <form action="<%= logout_path(:user_id => current_user.id) %>" method="post">
            <input name="_method" type="hidden" value="DELETE">
            <button type="submit" class="btn btn-link btn-space-8">ログアウト</button>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          </form>
        </li>
        <% else %>
        <li><a href="<%= login_path %>">ログイン</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/message' %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script>
    $(document).ready(function(){
      $(".btn-danger").click(function(e){
        if(!confirm("本当に削除しますか？")){
          e.preventDefault();
          return false;
        }
        return true;
      });
    });

    window.scrollTo(0,document.body.scrollHeight);
    </script>
  </body>
</html>

app/views/posts/index.html.erb
<% content_for :title do %>
トーク画面
<% end %>

<div class="row">
  <div class="col-md-8 col-md-offset-2 well">
    <form action="<%= delete_all_post_path %>" method="post">
      <button type="submit" class="btn btn-danger btn-xs pull-right">削除</button>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    </form>

    <% @posts.each do |post| %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object img-circle" src="<%= "/images/#{post.user.image}" %>" width=64 height=64>
        </a>
      </div>
      <div class="media-body">
        <h5 class="media-heading"><%= post.user.name %>　<small><%= post.created_at %></small></h5>
        <p><%= post.message %></p>
      </div>
    </div>
    <% end %>

    <a href="<%= new_post_path %>" class="btn btn-primary btn-space-30 btn-block">メッセージ作成</a>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for :title do %>
メッセージ作成
<% end %>

<%= render 'layouts/error_message', object: @post %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>メッセージ作成</h1>
    <form action="<%= posts_path %>" method="post">
      <div class="form-group">
        <label for="Message">メッセージ</label>
        <textarea class="form-control" name="message" id="Message" rows="5" placeholder="Your Post"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">送信</button>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    </form>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title do %>
登録情報修正
<% end %>

<%= render 'layouts/error_message', object: @user %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>登録情報修正</h1>
    <p><strong>修正する箇所のみ入力してください</strong></p>
    <form action="<%= user_path(@user.id) %>" method="post" enctype="multipart/form-data">
      <input name="_method" type="hidden" value="PUT">
      <div class="form-group">
        <label for="Name">名前</label>
        <input type="text" name="name" class="form-control" id="Name">
      </div>
      <div class="form-group">
        <label for="Email">Eメール</label>
        <input type="text" name="email" class="form-control" id="Email">
      </div>
      <div class="form-group">
        <label for="Password">パスワード</label>
        <input type="password" name="password" class="form-control" id="Password">
      </div>
      <div class="form-group">
        <label for="ImageFile">新しいプロフィール画像ファイル</label>
        <input type="file" name="file" id="ImageFile">
      </div>
      <button type="submit" class="btn btn-primary">修正</button>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    </form>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :title do %>
登録
<% end %>

<%= render 'layouts/error_message', object: @user %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>登録</h1>
    <form action="<%= users_path %>" method="post" enctype="multipart/form-data">
      <div class="form-group">
        <label for="Name">名前</label>
        <input type="text" name="name" class="form-control" id="Name" placeholder="Name">
      </div>
      <div class="form-group">
        <label for="Email">Eメール</label>
        <input type="text" name="email" class="form-control" id="Email" placeholder="Email">
      </div>
      <div class="form-group">
        <label for="Password">パスワード</label>
        <input type="password" name="password" class="form-control" id="Password" placeholder="Password">
      </div>
      <div class="form-group">
        <label for="ImageFile">プロフィール画像ファイル</label>
        <input type="file" name="file" id="ImageFile">
      </div>
      <button type="submit" class="btn btn-primary">登録</button>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    </form>
  </div>
</div>